// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skmfggeirhuanrdiepha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrbWZnZ2Vpcmh1YW5yZGllcGhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3MDg2NDgsImV4cCI6MjA3ODI4NDY0OH0.La_yFYjiZTtMz3b1RGETV7FvN8Xf7bCVO1uX5bzHoks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});